### ISSUE TITLE
Clarification of event coordinates

### ISSUE THREAD

**Issue by dzineit** [statsbomb/open-data#7]
Reading the documentation pretty thoroughly I understand the way the pitch coordinates work, however (and apologies if I've just missed something here) I can't find anything which clarifies which direction each team is playing in.

Is the home team always playing from 0 -> 120? Does the home team always start playing from 0 -> 120 but then this is flipped at half time? Is there a data point which contains which direction each team is playing in?

My particular use case is determining whether a pass is going into the attacking third.

**Comment by deepxg** [comment]
The coordinates are always in terms of the team identified in the event, with 120 their opponent's goal line.

**Comment by dzineit** [comment]
Ah wonderful, many thanks. I had started to suspect that was the case from experimenting with it but confirmation is nice!

**Comment by goodalld10** [comment]
I understand that the StatsBomb's coordinate system is set up so that a player's team always attacks toward the right side of the field, irrespective of whether they are playing at home or away. I read somewhere that this is dependent on certain play types. 

In my research, I would like the events to occur on the original side of the pitch. I tried using team.id to flip the locations back to "normal" but unfortunately, this does not fix the issue. 

I was wondering if there was any way to get access to the list of play types that impact the coordinate locations or if anyone figured out a way to return the flipped frames back to the original ones.

**Comment by deepxg** [comment]
It's not dependent on anything other than the team ID - do you have an example of somewhere the flipping results in the wrong coordinates?

**Comment by goodalld10** [comment]
I am working with the the 2022 UEFA European Women’s Championship data and in particular the game between Spain (ID 863) and Germany (ID 857) (matchID = 3835330). I have animated the game without any changes and if we focus just on the first half of the game, the first frame has 863 attacking to the 120 goal line and 857 attacking to the 0 goal line. 

I flipped any frame that had team.id == 857 and this fixed a lot of issues but here are a few examples that did not get corrected: 

Row 9: Foul Won, team.id = 863
Row 26: Duel, team.id = 857
Row 47: Ball Receipt*, team.id = 863
Row 53: Dribbled Past, team.id = 863
Row 58: Dispossessed, team.id = 863

I thought maybe these were exceptions based on the event.type outcome but I cant seem to figure it out. 
If you need to see code or anything please let me know. ( we may need to move offline as I am struggling to add files here)
